export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const userConstant = {
  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",

  GET_USERS_BY_ID_REQUEST: "GET_USERS_BY_ID_REQUEST",
  GET_USERS_BY_ID_SUCCESS: "GET_USERS_BY_ID_SUCCESS",
  GET_USERS_BY_ID_FAILURE: "GET_USERS_BY_ID_FAILURE",

  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",

  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
};

export const productConstants = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",

  GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",

  GET_INSLIDER_PRODUCTS_SUCCESS: "GET_INSLIDER_PRODUCTS_SUCCESS",
  GET_ISHOT_PRODUCTS_SUCCESS: "GET_ISHOT_PRODUCTS_SUCCESS",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",
};

export const orderConstants = {
  GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
  GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
  GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",

  GET_CUSTOM_ORDER_BY_ID_REQUEST: "GET_CUSTOM_ORDER_BY_ID_REQUEST",
  GET_CUSTOM_ORDER_BY_ID_SUCCESS: "GET_CUSTOM_ORDER_BY_ID_SUCCESS",
  GET_CUSTOM_ORDER_BY_ID_FAILURE: "GET_CUSTOM_ORDER_BY_ID_FAILURE",

  GET_CARED_ORDERS_REQUEST: "GET_CARED_ORDERS_REQUEST",
  GET_CARED_ORDERS_SUCCESS: "GET_CARED_ORDERS_SUCCESS",
  GET_CARED_ORDERS_FAILURE: "GET_CARED_ORDERS_FAILURE",

  GET_UNCARED_ORDERS_REQUEST: "GET_UNCARED_ORDERS_REQUEST",
  GET_UNCARED_ORDERS_SUCCESS: "GET_UNCARED_ORDERS_SUCCESS",
  GET_UNCARED_ORDERS_FAILURE: "GET_UNCARED_ORDERS_FAILURE",

  MANAGER_SEARCH_ORDER_REQUEST: "MANAGER_SEARCH_ORDER_REQUEST",
  MANAGER_SEARCH_ORDER_SUCCESS: "MANAGER_SEARCH_ORDER_SUCCESS",
  MANAGER_SEARCH_ORDER_FAILURE: "MANAGER_SEARCH_ORDER_FAILURE",

  UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
  UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
  UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",

  GET_CUSTOMER_ORDER_BYEMAIL_REQUEST: "GET_CUSTOMER_ORDER_BYEMAIL_REQUEST",
  GET_CUSTOMER_ORDER_BYEMAIL_SUCCESS: "GET_CUSTOMER_ORDER_BYEMAIL_SUCCESS",
  GET_CUSTOMER_ORDER_BYEMAIL_FAILURE: "GET_CUSTOMER_ORDER_BYEMAIL_FAILURE",

  SORT_ORDER_REQUEST: " SORT_ORDER_REQUEST",
  SORT_ORDER_SUCCESS: " SORT_ORDER_SUCCESS",
  SORT_ORDER_FAILURE: " SORT_ORDER_FAILURE",
};

export const postConstant = {
  CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

  GET_POST_REQUEST: " GET_POST_REQUEST",
  GET_POST_SUCCESS: " GET_POST_SUCCESS",
  GET_POST_FAILURE: " GET_POST_FAILURE",

  GET_POST_BY_ID_REQUEST: "GET_POST_BY_ID_REQUEST",
  GET_POST_BY_ID_SUCCESS: "GET_POST_BY_ID_SUCCESS",
  GET_POST_BY_ID_FAILURE: "GET_POST_BY_ID_FAILURE",

  UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAILURE: "UPDATE_POST_FAILURE",
};

export const reportConstant = {
  GET_REPORT_REQUEST: "GET_REPORT_REQUEST",
  GET_REPORT_SUCCESS: "GET_REPORT_SUCCESS",
  GET_REPORT_FAILURE: "GET_REPORT_FAILURE",

  GET_ADVANGE_REPORTS_REQUEST: "GET_ADVANGE_REPORTS_REQUEST",
  GET_ADVANGE_REPORTS_SUCCESS: "GET_ADVANGE_REPORTS_SUCCESS",
  GET_ADVANGE_REPORTS_FAILURE: "GET_ADVANGE_REPORTS_FAILURE",

  UPDATE_CHECK_REPORT_REQUEST: "UPDATE_CHECK_REPORT_REQUEST",
  UPDATE_CHECK_REPORT_SUCCESS: "UPDATE_CHECK_REPORT_SUCCESS",
  UPDATE_CHECK_REPORT_FAILURE: "UPDATE_CHECK_REPORT_FAILURE",
};

export const newConstant = {
  SEND_NEW_REQUEST: "SEND_NEW_REQUEST",
  SEND_NEW_SUCCESS: "SEND_NEW_SUCCESS",
  SEND_NEW_FAILURE: "SEND_NEW_FAILURE",

  GET_NEW_REQUEST: " GET_NEW_REQUEST",
  GET_NEW_SUCCESS: " GET_NEW_SUCCESS",
  GET_NEW_FAILURE: "GET_NEW_FAILURE",
};

export const summaryConstant = {
  GET_TOP_SALES_REQUEST: "GET_TOP_SALES_REQUEST",
  GET_TOP_SALES_SUCCESS: "GET_TOP_SALES_SUCCESS",
  GET_TOP_SALES_FAILURE: "GET_TOP_SALES_FAILURE",

  GET_SALES_BY_DAY_REQUEST: "GET_SALES_BY_DAY_REQUEST",
  GET_SALES_BY_DAY_SUCCESS: "GET_SALES_BY_DAY_SUCCESS",
  GET_SALES_BY_DAY_FAILURE: "GET_SALES_BY_DAY_FAILURE",

  GET_SALES_BY_MONTH_REQUEST: "GET_SALES_BY_MONTH_REQUEST",
  GET_SALES_BY_MONTH_SUCCESS: "GET_SALES_BY_MONTH_SUCCESS",
  GET_SALES_BY_MONTH_FAILURE: "GET_SALES_BY_MONTH_FAILURE",

  GET_POP_TAGS_REQUEST: "GET_POP_TAGS_REQUEST",
  GET_POP_TAGS_SUCCESS: "GET_POP_TAGS_SUCCESS",
  GET_POP_TAGS_FAILURE: "GET_POP_TAGS_FAILURE",
};
